// app-vue/src/App.vue
<template>
  <div class="card-wrapper">
    <poc-card text="Stencil Component">
      <div class="flex">
        <poc-button @click="increment" text="+" appearance="primary"></poc-button>
        <poc-input placeholder="0" :value="state.count"></poc-input>
        <poc-button @click="increment" text="-" appearance="primary"></poc-button>
      </div>
    </poc-card>
  </div>
</template>

<script setup lang="ts">

import { reactive } from 'vue'

const state = reactive({ count: 0 })

function increment() {
  state.count++
}

</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

.flex{
  display: flex;
}

.card-wrapper{
  max-width: 350px;
}
</style>

// app-react/src/App.tsx
import React from 'react';
import logo from './logo.svg';

function App() {
  const [count, setCount] = React.useState(0);

  const add = () => {
    setCount(count + 1);
  }

  const subtract = () => {
    setCount(count - 1);
  }
  return (
    <div className="App">
      <div style={{maxWidth: '400px'}}>
        <poc-card text="Stencil Component">
          <div style={{display: 'flex', }}>
            <poc-button onClick={() => add()} text="+" appearance="primary" />
            <poc-input placeholder="0" value={count}/>
            <poc-button onClick={() => subtract()} text="-" appearance="primary" />
          </div>
        </poc-card>
      </div>
    </div>
  );
}

export default App;
